# Generated by Django 3.2.14 on 2023-02-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_delete_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmethistory',
            old_name='Disese',
            new_name='Disease',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='Treatment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
