# Generated by Django 5.0.1 on 2024-02-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_auto_20230221_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='maternity_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
