# Generated by Django 5.0.1 on 2024-02-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_doctorlist_doctirid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255)),
                ('foodimage', models.FileField(upload_to='food_image')),
                ('calories', models.FloatField()),
                ('nutrition', models.CharField(choices=[('Carbohydrates', 'Carbohydrates'), ('Proteins', 'Proteins'), ('Fats', 'Fats'), ('Vitamins', 'Vitamins'), ('Minerals', 'Minerals'), ('Dietary fiber', 'Dietary fiber'), ('Water', 'Water')], max_length=255)),
                ('timester', models.CharField(choices=[('1-4 weeks', '1-4 weeks'), ('5-8 weeks', '5-8 weeks'), ('9-13 weeks', '9-13 weeks'), ('14-17 weeks', '14-17 weeks'), ('18-22 weeks', '18-22 weeks'), ('23-27 weeks', '23-27 weeks'), ('28-31 weeks', '28-31 weeks'), ('32-35 weeks', '32-35 weeks'), ('36-40 weeks', '36-40 weeks')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutname', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('workoutimage', models.FileField(upload_to='workout_image')),
                ('timester', models.CharField(choices=[('1-4 weeks', '1-4 weeks'), ('5-8 weeks', '5-8 weeks'), ('9-13 weeks', '9-13 weeks'), ('14-17 weeks', '14-17 weeks'), ('18-22 weeks', '18-22 weeks'), ('23-27 weeks', '23-27 weeks'), ('28-31 weeks', '28-31 weeks'), ('32-35 weeks', '32-35 weeks'), ('36-40 weeks', '36-40 weeks')], max_length=255)),
            ],
        ),
    ]
