# Generated by Django 5.0.1 on 2024-02-16 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('MRP', models.IntegerField()),
                ('image', models.FileField(upload_to='medicine_image')),
                ('timester', models.CharField(choices=[('1-4 weeks', '1-4 weeks'), ('5-8 weeks', '5-8 weeks'), ('9-13 weeks', '9-13 weeks'), ('14-17 weeks', '14-17 weeks'), ('18-22 weeks', '18-22 weeks'), ('23-27 weeks', '23-27 weeks'), ('28-31 weeks', '28-31 weeks'), ('32-35 weeks', '22-35 weeks'), ('36-40 weeks', '36-40 weeks')], max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
