# Generated by Django 5.0.1 on 2024-02-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0003_cartitems_checkoutitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timester',
            field=models.CharField(choices=[('1-4 weeks', '1-4 weeks'), ('5-8 weeks', '5-8 weeks'), ('9-13 weeks', '9-13 weeks'), ('14-17 weeks', '14-17 weeks'), ('18-22 weeks', '18-22 weeks'), ('23-27 weeks', '23-27 weeks'), ('28-31 weeks', '28-31 weeks'), ('32-35 weeks', '32-35 weeks'), ('36-40 weeks', '36-40 weeks')], max_length=255),
        ),
    ]
